---
title: "Historial"
author: "Cesar"
date: "16/9/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}


#Se establecen las librerias
library(tidyverse)
library(lubridate)
library(textcat)

#Se obtiene el archivo excel y se convierte a dataframe
his <- read_csv("C:/Users/G50/Desktop/Cesar' Shit/RecommenderSystem/Datasets_Originales/ORIGINAL_HISTORIAL.csv", locale = readr::locale(encoding = "latin1"))

#his <- data.frame(lapply(his, as.character), stringsAsFactors=FALSE)

#Se utiliza para verificar la estructura del dataset
#str(his)

# Se cuenta el numero lineas que contiene el dataset
nrow(his)

#Elimina las bibliotecas que no pertenecen a Ciudad del conocimiento
BCC <- his[grepl("BCC", his$Ubicacion),]
nrow(BCC)
oBCC <- BCC[!grepl("SRBCC", BCC$Ubicacion),]


#Se arreglan errores respecto a la columna CARRERA
oBCC$Carrera
oBCC$Carrera <- gsub("Programa de ", "", oBCC$Carrera)
oBCC$Carrera <- gsub("HECHO", "", oBCC$Carrera)
oBCC$Carrera <- gsub("[0-9]*", "", oBCC$Carrera)
oBCC$Carrera <- gsub("HEHCO", "", oBCC$Carrera)
oBCC$Carrera <- gsub("Lic.", "Licenciatura", oBCC$Carrera)
oBCC$Carrera <- gsub("Licenciaturanciatura", "Licenciatura", oBCC$Carrera)
                      

try <- oBCC
try['ISBN']
str(try)

#Corrigen datos de la columna ISBN
oBCC$ISBN <- str_sub(try$ISBN, end = 13)
oBCC$ISBN <- gsub("[a-z, A-Z, ?]*", "", oBCC$ISBN)
oBCC$ISBN <- gsub("[-, !, @, #, $, %, ^, &, , *, :, -, ., ;, /]", "", oBCC$ISBN)

#--------- Reading the data
#uacj_library <- read_csv("C:/Users/G50/Documents/R pRogRams/RecommenderSystem/Historial.csv", 
 #                        locale = readr::locale(encoding = "latin1"))

oBCC %>% glimpse()

#--------- Changing upper to lower case
oBCC$Titulo <-tolower(oBCC$Titulo)

oBCC %>% glimpse()

#--------- Cleaning function
rm_accent <- function(str,pattern="all") {
   if(!is.character(str))
    str <- as.character(str)

  pattern <- unique(pattern)

  if(any(pattern=="?"))
    pattern[pattern=="?"] <- "?"

  symbols <- c(
    acute = "????????????",
    grave = "??????????",
    circunflex = "??????????",
    tilde = "??????",
    umlaut = "???????????",
    cedil = "??"
  )

  nudeSymbols <- c(
    acute = "aeiouAEIOUyY",
    grave = "aeiouAEIOU",
    circunflex = "aeiouAEIOU",
    tilde = "aoAOnN",
    umlaut = "aeiouAEIOUy",
    cedil = "cC"
  )

  accentTypes <- c("?","`","^","~","?","?")

  if(any(c("all","al","a","todos","t","to","tod","todo")%in%pattern)) # opcao retirar todos
    return(chartr(paste(symbols, collapse=""), paste(nudeSymbols, collapse=""), str))

  for(i in which(accentTypes%in%pattern))
    str <- chartr(symbols[i],nudeSymbols[i], str) 

  return(str)
}


rm_accent(oBCC$Titulo)

#uacj_library %>% View()

#--------- Creating a column for language reference
oBCC <- oBCC %>% 
  mutate(language_reference = textcat(oBCC$Titulo))

oBCC %>% glimpse()  %>% View()


#write.csv(oBCC, file = "historial_clean.csv")

#Se crea la columna instituto
oBCC$Instituto<- NA

oBCC$Instituto <- oBCC$Carrera

#Variable utilizada para visualizar los datos

oBCC %>% select(1,6) %>% View()

#Limpiano columna Carrera
oBCC$Carrera <- gsub("HEHCO  ", "", oBCC$Carrera)
oBCC$Carrera <- gsub("Licenciatura en Literatura-Hispanomexicana", "Licenciatura en Literatura Hispanomexicana", oBCC$Carrera)
oBCC$Carrera <- gsub("Licenciatura Periodismo", "Licenciatura en Periodismo", oBCC$Carrera)
oBCC$Carrera <- gsub("Carrera de Licenciaturanciado", "Licenciatura ", oBCC$Carrera)
oBCC$Carrera <- gsub("Licenciatura Administracion de Empresas", "Licenciatura en Administracion de Empresas", oBCC$Carrera)
oBCC$Carrera <- gsub("P. LIC. DERECHO", "Licenciatura en Derecho", oBCC$Carrera)
oBCC$Carrera <- gsub("Maestr¡a en Administraci¢n", "Maestria en Administración", oBCC$Carrera)
oBCC$Carrera <- gsub("Licenciatura de Diseno Industrial", "Licenciatura de Diseño Industrial", oBCC$Carrera)
oBCC$Carrera <- gsub("Arquitectura", "Licenciatura en Arquitectura", oBCC$Carrera)
oBCC$Carrera <- gsub("Licenciatura en Ingeniería Mecánica", "Ingeniería Mecánica", oBCC$Carrera)
oBCC$Carrera <- gsub("ING. SISTEMAS DIGITALES Y COMUNICACIONES", "Ingeniería en Sistemas Digitales", oBCC$Carrera)
oBCC$Carrera <- gsub("Diseño digital", "Licenciatura en Diseño Digital de Medios Interactivos", oBCC$Carrera)
oBCC$Carrera <- gsub("Licenciatura en Ingeniería Mecánica", "Ingeniería Mecánica", oBCC$Carrera)
oBCC$Carrera <- gsub("QUIMICO FARMACO BIOLOGO", "Licenciatura en Químico Farmacéutico Biólogo", oBCC$Carrera)
oBCC$Carrera <- gsub("QFB", "Licenciatura en Químico Farmacéutico Biólogo", oBCC$Carrera)
oBCC$Carrera <- gsub("Contabilidad", "Contaduría", oBCC$Carrera)
oBCC$Carrera <- gsub("P LIC. NUTRICION", "Licenciatura en Nutrición", oBCC$Carrera)
oBCC$Carrera <- gsub("P. LIC. NUTRICION", "Licenciatura en Nutrición", oBCC$Carrera)
oBCC$Carrera <- gsub("Médico Cirujano", "Licenciatura en Médico Cirujano", oBCC$Carrera)
oBCC$Carrera <- gsub("Maestr¡a en Educaci¢n ", "Maestria en Educación ", oBCC$Carrera)
oBCC$Carrera <- gsub("¡", "i", oBCC$Carrera)
oBCC$Carrera <- gsub("Licenciatura en Ingeniería Ambiental", "Ingeniería Ambiental", oBCC$Carrera)
oBCC$Carrera <- gsub("Mtria.", "Maestría", oBCC$Carrera)
oBCC$Carrera <- gsub("LIC. EN FINANZAS", "Licenciatura en Finanzas", oBCC$Carrera)
oBCC$Carrera <- gsub("Licenciatura Medico Cirujano", "Licenciatura en Medico Cirujano", oBCC$Carrera)
oBCC$Carrera <- gsub("programa lic.", "Licenciatura", oBCC$Carrera)
oBCC$Carrera <- gsub("Licenciatura en Matem ticas", "Licenciatura en Matematicas", oBCC$Carrera)
oBCC$Carrera <- gsub("Licenciatura en Ingeniería en Energía y Mantenimiento Industrial", "Ingeniería en Energía y Mantenimiento Industrial", oBCC$Carrera)
oBCC$Carrera <- gsub("¢", "ó", oBCC$Carrera)
oBCC$Carrera <- gsub("Licenciaturanciado", "Licenciatura", oBCC$Carrera)
oBCC$Carrera <- gsub("Carrera de Ingeniero Electricista", "Ingeniería Electrica", oBCC$Carrera)
oBCC$Carrera <- gsub("Cirujano Dentista", "Licenciatura en Cirujano Dentista", oBCC$Carrera)
oBCC$Carrera <- gsub("Licenciatura de Diseno Indus/al@alumnos.uacj.mx/", "Licenciatura en Diseño Industrial", oBCC$Carrera)
oBCC$Carrera <- gsub("Carrera de Arquitecto", "Licenciatura en arquitectura", oBCC$Carrera)
oBCC$Carrera <- gsub("Licenciatura en Qimico Farmaco Biologo", "Licenciatura en Químico Fármaco Biólogo", oBCC$Carrera)
oBCC$Instituto <- gsub("HEHCO", "", oBCC$Instituto)


#Se asocia el instituto IIT a las carreras que pertenecen ahi
oBCC$Instituto <- gsub("Ingeniería en Sistemas Automotrices", "IIT", oBCC$Instituto)
oBCC$Instituto <- gsub("Ingeniería Civil", "IIT", oBCC$Instituto)
oBCC$Instituto <- gsub("Ingeniería Industrial y de Sistemas", "IIT", oBCC$Instituto)
oBCC$Instituto <- gsub("Ingeniería de Software", "IIT", oBCC$Instituto)
oBCC$Instituto <- gsub("Ingeniería en Sistemas Computacionales", "IIT", oBCC$Instituto)
oBCC$Instituto <- gsub("Ingeniería Industrial y de Sistemas", "IIT", oBCC$Instituto)
oBCC$Instituto <- gsub("Ingeniería en Mecatrónica", "IIT", oBCC$Instituto)
oBCC$Instituto <- gsub("Maestria en Ingenieria Industrial", "IIT", oBCC$Instituto)
oBCC$Instituto <- gsub("Ingeniería Mecánica", "IIT", oBCC$Instituto)
oBCC$Instituto <- gsub("Ingeniería en Sistemas Digitales", "IIT", oBCC$Instituto)
oBCC$Instituto <- gsub("Ingeniería Ambiental", "IIT", oBCC$Instituto)
oBCC$Instituto <- gsub("Ingeniería en Energía y Mantenimiento Industrial", "IIT", oBCC$Instituto)
oBCC$Instituto <- gsub("Ingeniería Electrica", "IIT", oBCC$Instituto)
oBCC$Instituto <- gsub("Ingeniería Biomédica", "IIT", oBCC$Instituto)
oBCC$Instituto <- gsub("Ingeniería Telemática", "IIT", oBCC$Instituto)
oBCC$Instituto <- gsub("Doctorado en Ciencias en Ingenieria", "IIT", oBCC$Instituto)
oBCC$Instituto <- gsub("Ingeniería en Sistemas Digitales", "IIT", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en IIT", "IIT", oBCC$Instituto)
oBCC$Instituto <- gsub("IIT y Comunicaciones", "IIT", oBCC$Instituto)


#Se asocia el instituto ICSA a las carreras que pertenecen ahi
oBCC$Instituto <- gsub("Licenciatura en Derecho", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("programa lic. en Derecho", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("P. LIC. DERECHO", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Educación ", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Psicología", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Carrera de Licenciaturanciado en Psícologia", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Educación", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Trabajo Social", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Periodismo", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura Periodismo", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Comercio Exterior", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Maestria en Psicología", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura  en Administración de Empresas", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Administración de Empresas", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Turismo", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Contaduría", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Pedagogía del Inglés como segunda lengua", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Literatura-Hispanomexicana", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Enseñanza del Inglés", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Finanzas", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura Administracion de Empresas", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Carrera de Licenciaturanciado en Administración de Empresas", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Maestr¡a en Administraci¢n", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Historia", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Economía", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Finanzas", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Sociologa", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Maestría en Psicología", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Arquitectura", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Carrera de Licenciaturanciado de Economia", "ICSA", oBCC$Instituto)
oBCC$Instituto <- gsub("Maestría en investigacion educativa", "ICSA", oBCC$Instituto)

#Se asocia el instituto IADA a las carreras que pertenecen ahi
oBCC$Instituto <- gsub("Licenciatura en Diseño Gráfico", "IADA", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Diseño Industrial", "IADA", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura de Diseno Indus/al@alumnos.uacj.mx/", "IADA", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Publicidad", "IADA", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Diseño de Interiores", "IADA", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Arquitectura", "IADA", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Diseño Digital de Medios Interactivos", "IADA", oBCC$Instituto)
oBCC$Instituto <- gsub("Maestría en Estudios y Procesos Creativos", "IADA", oBCC$Instituto)
oBCC$Instituto <- gsub("Diseño digital", "IADA", oBCC$Instituto)
oBCC$Instituto <- gsub("Carrera de Licenciaturanciado en Diseño Gráfico", "IADA", oBCC$Instituto)

#Se asocia el instituto ICB a las carreras que pertenecen ahi
oBCC$Instituto <- gsub("Licenciatura en Gerontología", "ICB", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Nutrición", "ICB", oBCC$Instituto)
oBCC$Instituto <- gsub("P. LIC. NUTRICION", "ICB", oBCC$Instituto)
oBCC$Instituto <- gsub("P LIC. NUTRICION", "ICB", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Enfermería", "ICB", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Químico Farmacéutico Biólogo", "ICB", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Químico Fármaco Biólogo", "ICB", oBCC$Instituto)
oBCC$Instituto <- gsub("QUIMICO FARMACO BIOLOGO", "ICB", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Entrenamiento Deportivo", "ICB", oBCC$Instituto)
oBCC$Instituto <- gsub("Médico Veterinario Zootecnista", "ICB", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Biologia", "ICB", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Cirujano Dentista", "ICB", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Quimica", "ICB", oBCC$Instituto)
oBCC$Instituto <- gsub("Licenciatura en Biología", "ICB", oBCC$Instituto)



write.csv(oBCC, file = "historial_clean.csv")

oBCC %>% select(1,6) %>% View()


  #Cambia la columna de idioma a SPANISH

  oBCC$language_reference <- gsub("latin", "spanish", oBCC$language_reference)
  oBCC$language_reference <- gsub("romanian", "spanish", oBCC$language_reference)
  oBCC$language_reference <- gsub("catalan", "spanish", oBCC$language_reference)
  oBCC$language_reference <- gsub("rumantsch", "spanish", oBCC$language_reference)
  oBCC$language_reference <- gsub("portuguese", "spanish", oBCC$language_reference)
  oBCC$language_reference <- gsub("tagalog", "spanish", oBCC$language_reference)
  oBCC$language_reference <- gsub("basque", "spanish", oBCC$language_reference)
  oBCC$language_reference <- gsub("italian", "spanish", oBCC$language_reference)
  oBCC$language_reference <- gsub("swahili", "spanish", oBCC$language_reference)
  oBCC$language_reference <- gsub("esperanto", "spanish", oBCC$language_reference)
  oBCC$language_reference <- gsub("serbian-ascii", "spanish", oBCC$language_reference)
  oBCC$language_reference <- gsub("slovak-windows1250", "spanish", oBCC$language_reference)
  oBCC$language_reference <- gsub("bosnian", "spanish", oBCC$language_reference)
  oBCC$language_reference <- gsub("croatian-ascii", "spanish", oBCC$language_reference)
  oBCC$language_reference <- gsub("estonian", "spanish", oBCC$language_reference)
  oBCC$language_reference <- gsub("finnish", "spanish", oBCC$language_reference)
  oBCC$language_reference <- gsub("latvian", "spanish", oBCC$language_reference)
  oBCC$language_reference <- gsub("lithuanian", "spanish", oBCC$language_reference)
  oBCC$language_reference <- gsub("icelandic", "spanish", oBCC$language_reference)
  oBCC$language_reference <- gsub("norwegian", "spanish", oBCC$language_reference)
  oBCC$language_reference <- gsub("sanskrit", "spanish", oBCC$language_reference)
  
  
  #Cambia la seccion idioma a ENGLISH
    oBCC$language_reference <- gsub("middle_english", "english", oBCC$language_reference)
    oBCC$language_reference <- gsub("polish", "english", oBCC$language_reference)
    oBCC$language_reference <- gsub("scots_gaelic", "english", oBCC$language_reference)
    oBCC$language_reference <- gsub("swedish", "english", oBCC$language_reference)
    oBCC$language_reference <- gsub("slovak-ascii", "english", oBCC$language_reference)
    oBCC$language_reference <- gsub("frisian", "english", oBCC$language_reference)
    oBCC$language_reference <- gsub("manx", "english", oBCC$language_reference)
    oBCC$language_reference <- gsub("afrikaans", "english", oBCC$language_reference)
    oBCC$language_reference <- gsub("welsh", "english", oBCC$language_reference)
  
    
    
#oBCC$language_reference <- gsub("", "spanish", oBCC$language_reference)
#str(oBCC)
#lalal <-  oBCC$language_reference <- as.factor(oBCC$language_reference)
#str(lalal)
# oBCC %>% filter(oBCC$language_reference == "german") %>% View()
#levels(lalal)
#oBCC$language_reference <- gsub("latin", "spanish", oBCC$language_reference)
#oBCC$language_reference <- gsub("romanian", "esperando", "spanish", #oBCC$language_reference)

spanish <- oBCC %>% 
  filter(language_reference == "spanish")
    write.csv(spanish, "historial_spanish.csv")
    
english <- oBCC %>%
  filter(language_reference == "english")
    write.csv(english, "hisorial_english.csv")
```

